import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';
import React from 'react';
import NavBar from '@/app/ui/NavBar';
import { auth } from '@/auth';
import SignOut from '@/app/ui/SignOut';
import Banner from '@/app/ui/banner/Banner';

const sora = Sora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${sora.className} bg-gradient-to-r from-white to-gray-300`}
      >
        <Banner />
        <NavBar email={session?.user?.email} image={session?.user?.image}>
          <SignOut />
        </NavBar>
        {children}
      </body>
    </html>
  );
}
