version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  sqlPostgresDb:
    container_name: postgresPV113
    image: postgres:16.1
    ports:
      - "5113:5432"
    environment:
      - POSTGRES_USER=userpv113
      - POSTGRES_PASSWORD=myStong_Pdk%dki934kIsassword123#
      - POSTGRES_DB=dbpv113
    networks:
      - myAppNetwork
    volumes:
      - /data/HackerNews/webvolume/postgresql:/var/lib/postgresql/data   
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  appaspapi:
    container_name: api_hn

    image: ihorsamolich/newsserver
    # build:
    #   context: ./hackernewsApi
    #   dockerfile: Dockerfile
    ports:
      - "5018:8080"
    networks:
      - myAppNetwork
    depends_on:
      - sqlPostgresDb
    volumes:
      - /data/HackerNews/webvolume/images:/app/images  # Use the volume name appvol here
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  clientnextjs:
    container_name: client_hn

    image: ihorsamolich/newsclient
    # build:
    #   context: ./hackernewsClient
    #   dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - appaspapi
    volumes:
      - /data/HackerNews/webvolume/client:/app/client
    networks:
      - myAppNetwork
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5